
// LOGIN
export const SET_LOGIN_FAILURE = 'SET_LOGIN_FAILURE'

// Register
export const SET_REGISTER_FAILURE = 'SET_REGISTER_FAILURE'
export const SET_FIRST_LEVEL_VISIBILITY = 'SET_FIRST_LEVEL_VISIBILITY'
export const SET_NOTIFICATION_STATE = 'SET_NOTIFICATION_STATE'
export const SET_USER_DETAIL = 'SET_USER_DETAIL'
export const SET_UNREAD_MESSAGE = 'SET_UNREAD_MESSAGE'



