export const SET_EMPLOYER_SHIFTS =   'SET_EMPLOYER_SHIFTS'
export const SET_NETWORK_CONTACTS = 'SET_NETWORK_CONTACTS'
export const SET_LOCATIONS = 'SET_LOCATIONS'
export const SET_CLEAR_STATE = 'SET_CLEAR_STATE'
export const SET_EMPLOYER_TIMESHEET = 'SET_EMPLOYER_TIMESHEET'



